server:
  port: 8080
  servlet:
    context-path: /jip/project

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3308/obss
    username: root
    password: Serra123.
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  resources:
    static-locations=classpath:/static/:

  main:
    banner-mode: off

  #logging:
  # level:
  #  root: info
logging:
  level:
    org.springframework.security: DEBUG